- hosts: all
  become: true
  pre_tasks:

- hosts: server1
  become: true
  tasks:
    - name: Copy PCAP file to Control node
      fetch:
        src: traffic.pcap
        dest: "/home/jgpaz/H0A8.1/PCAP"
    - block:
      - name: Verifying of Extraction
        shell: cat traffic.pcap
        register: traffic

    - debug:
        msg="{{traffic}}"
